name: Auto Tests
on: [push]

concurrency:
  group: ci-${{github.ref}}-autotests
  cancel-in-progress: true
  
jobs:
  linux_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y \
              python3-pip \
              python3-pytest \
              python3-gdal \
              libsqlite3-mod-spatialite
              
          pip3 install -r requirements.txt

      - name: run tests
        run: |
          cd workpackages
          python3 -m pytest ../
