name: Auto Tests
on: [push]
jobs:
  linux_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: install deps
        run: |
          sudo apt-get update && sudo apt-get install -y \
              python3-pip \
              python3-pytest \
              python3-sqlite3

      - name: run tests
        run: |
          python3 -m pytest
